name: Release & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    # TODO: Turn on once ready
    if: ${{ false }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create Core Release
        uses: elgohr/Github-Release-Action@v5
        id: create_release_core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Core"
          workdir: "packages/core"
      - name: Create Sqlite Release
        uses: elgohr/Github-Release-Action@v5
        id: create_release_sqlite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Sqlite"
          workdir: "packages/sqlite"

  publish:
    # TODO: Turn on once ready
    if: ${{ false }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm install
      - name: Build
        run: npm run build --workspaces
      - name: Publish to npm
        run: npm publish --workspaces --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@type-linq'
      - name: Publish to GitHub Packages
        run: npm publish --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}